services:
  calculator_client:
    build: ./calculator_client
    container_name: calculator_client_container
    networks:
      someip_net:
        ipv4_address: 10.10.0.2
    volumes:
      - ./build_output/main_runtime:/etc/threesomeip/bin/runtime:ro
      - ./calculator_client/someip.json:/etc/threesomeip/someip.json:ro
      - ./build_output/main_calculator_proxy:/etc/threesomeip/bin/calculator_client:ro
    entrypoint: ["sleep", "infinity"]
    stdin_open: true
    tty: true

  calculator_service:
    build: ./calculator_service
    container_name: calculator_service_container
    networks:
      someip_net:
        ipv4_address: 10.10.0.3
    volumes:
      - ./build_output/main_runtime:/etc/threesomeip/bin/runtime:ro
      - ./calculator_service/someip.json:/etc/threesomeip/someip.json:ro
      - ./build_output/main_calculator_stub:/etc/threesomeip/bin/calculator_service:ro
    entrypoint: ["sleep", "infinity"]
    stdin_open: true
    tty: true

networks:
  someip_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1